### PR TITLE
Switch to webpack

### LINKED ISSUE #118: BUG: Options are undefined
**Describe the bug**
The scripts are not loading; In fact, the entire extension is behaving pretty badly.

**To Reproduce**
1. Install the latest build (from 81-monorepo-integration).
2. Go to chrome://extensions (or any other chromium extension page) and watch the error.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows 10 21H1
- Browser Chrome
- Version 94

### LINKED ISSUE #120: FEATURE: Switch to webpack
While r.js is a good method to get production-ready code, its npm package hasn't been touched in [three years](https://github.com/requirejs/r.js). There are better, well-maintained packaging solutions, like [webpack](https://webpack.js.org/). I think we should switch to webpack for packaging scripts.

Here's the link to webpack's [docs](https://webpack.js.org/guides/getting-started/). We also need to use its [node api](https://webpack.js.org/api/node/).

Here's some of the things we need to do:
- [ ] Move window defs to initialization.
- [ ] Build scripts in development mode unless a flag is set.
- [ ] Always generate source maps.

### PR DESCRIPTION
**Pull request by nicolas377**
Please fill in this template.

- [x] Use a meaningful title for the pull request.
- [x] Test the change. (Compile and use the built extension.)
- [x] Run `npm run build`.
- [x] Run `npm test`.

Todo before merging:
- [x] Generate map files
- [x] Ignore built scripts in CodeQL
- [x] Solve #118

closes #120, closes #118

### CODE REVIEW

**Comment by Guy-Adler** [comment]
The fix to #118 will be in this pull request.

**Comment by Guy-Adler** [comment]
Source maps are only available when using the debug build, to save space and produce more reliable code. In addition, built source maps aren't linked well to the files themselves (chrome doesn't find them).

**Review by Guy-Adler — APPROVED** [review]
I wrote the code, so I don't think my approval is enough to merge this. @nicolas377 do you mind testing the extension to make sure I didn't oversee anything?

**Review by Guy-Adler — APPROVED** [review]
I wrote the code, so I don't think my approval is enough to merge this. @nicolas377 do you mind testing the extension to make sure I didn't oversee anything?

**Comment by nicolas377** [comment]
I'm not allowed to approve or request changes on my own PR, but I'd block this for now, since node 17.0.1 is running into an error with webpack:
https://github.com/webpack/webpack/issues/14532
image

**Comment by nicolas377** [comment]
Fixed locally with no changes, I'm good to merge!

**Pull request merged**
